// Liste de tous les pays d'Afrique avec leurs codes ISO
export const africanCountries = [
  { name: 'Algérie', code: 'dz', iso: 'DZ' },
  { name: 'Angola', code: 'ao', iso: 'AO' },
  { name: 'Bénin', code: 'bj', iso: 'BJ' },
  { name: 'Botswana', code: 'bw', iso: 'BW' },
  { name: 'Burkina Faso', code: 'bf', iso: 'BF' },
  { name: 'Burundi', code: 'bi', iso: 'BI' },
  { name: 'Cameroun', code: 'cm', iso: 'CM' },
  { name: 'Cap-Vert', code: 'cv', iso: 'CV' },
  { name: 'République centrafricaine', code: 'cf', iso: 'CF' },
  { name: 'Tchad', code: 'td', iso: 'TD' },
  { name: 'Comores', code: 'km', iso: 'KM' },
  { name: 'Congo', code: 'cg', iso: 'CG' },
  { name: 'RD Congo', code: 'cd', iso: 'CD' },
  { name: 'Côte d\'Ivoire', code: 'ci', iso: 'CI' },
  { name: 'Djibouti', code: 'dj', iso: 'DJ' },
  { name: 'Égypte', code: 'eg', iso: 'EG' },
  { name: 'Guinée équatoriale', code: 'gq', iso: 'GQ' },
  { name: 'Érythrée', code: 'er', iso: 'ER' },
  { name: 'Eswatini', code: 'sz', iso: 'SZ' },
  { name: 'Éthiopie', code: 'et', iso: 'ET' },
  { name: 'Gabon', code: 'ga', iso: 'GA' },
  { name: 'Gambie', code: 'gm', iso: 'GM' },
  { name: 'Ghana', code: 'gh', iso: 'GH' },
  { name: 'Guinée', code: 'gn', iso: 'GN' },
  { name: 'Guinée-Bissau', code: 'gw', iso: 'GW' },
  { name: 'Kenya', code: 'ke', iso: 'KE' },
  { name: 'Lesotho', code: 'ls', iso: 'LS' },
  { name: 'Liberia', code: 'lr', iso: 'LR' },
  { name: 'Libye', code: 'ly', iso: 'LY' },
  { name: 'Madagascar', code: 'mg', iso: 'MG' },
  { name: 'Malawi', code: 'mw', iso: 'MW' },
  { name: 'Mali', code: 'ml', iso: 'ML' },
  { name: 'Mauritanie', code: 'mr', iso: 'MR' },
  { name: 'Maurice', code: 'mu', iso: 'MU' },
  { name: 'Maroc', code: 'ma', iso: 'MA' },
  { name: 'Mozambique', code: 'mz', iso: 'MZ' },
  { name: 'Namibie', code: 'na', iso: 'NA' },
  { name: 'Niger', code: 'ne', iso: 'NE' },
  { name: 'Nigeria', code: 'ng', iso: 'NG' },
  { name: 'Rwanda', code: 'rw', iso: 'RW' },
  { name: 'São Tomé-et-Príncipe', code: 'st', iso: 'ST' },
  { name: 'Sénégal', code: 'sn', iso: 'SN' },
  { name: 'Seychelles', code: 'sc', iso: 'SC' },
  { name: 'Sierra Leone', code: 'sl', iso: 'SL' },
  { name: 'Somalie', code: 'so', iso: 'SO' },
  { name: 'Afrique du Sud', code: 'za', iso: 'ZA' },
  { name: 'Soudan du Sud', code: 'ss', iso: 'SS' },
  { name: 'Soudan', code: 'sd', iso: 'SD' },
  { name: 'Tanzanie', code: 'tz', iso: 'TZ' },
  { name: 'Togo', code: 'tg', iso: 'TG' },
  { name: 'Tunisie', code: 'tn', iso: 'TN' },
  { name: 'Ouganda', code: 'ug', iso: 'UG' },
  { name: 'Zambie', code: 'zm', iso: 'ZM' },
  { name: 'Zimbabwe', code: 'zw', iso: 'ZW' },
];

